### PR TITLE
Fix keychain issue

### LINKED ISSUE #17: Check react-native-keychain implementation
Doing some tests in a real iOS device, I realised it is not checking my biometrics (Face ID) anymore when opening a wallet or sending a transaction.

Need to verify implementation is correct in all cases (Face ID not available, Touch ID, etc.).

Haven't had the chance to test this in Android.

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes #17 on iOS real device and iOS simulator 15.4. Apparently there is a bug on the library with older 15.x versions of the simulator.

Haven't tested on Android.

### CODE REVIEW

File: utils/Keychain.tsx [hunk 1]
```diff
@@ -1,19 +1,23 @@
...
-    accessible: Keychain.ACCESSIBLE.WHEN_PASSCODE_SET_THIS_DEVICE_ONLY,
+    accessible: Keychain.ACCESSIBLE.AFTER_FIRST_UNLOCK,
     storage: Keychain.STORAGE_TYPE.RSA,
   });
 
   //const appBundleId = await DeviceInfo.getBundleId();
 
   useEffect(() => {
     Keychain.getSupportedBiometryType({}).then(biometryType => {
+      console.log(biometryType);
```
Comment (tsejerome) [inline utils/Keychain.tsx:20]: console.log cud be removed

**Comment by tsejerome** [comment]
will test on emulator later tmr

File: utils/Keychain.tsx (hunk 1 above)
Comment (aguycalled) [reply utils/Keychain.tsx]: removed
