### PR TITLE
Fixes QR parsing and generation with `navcoin:` prefix 

### LINKED ISSUE #36: Fix QR code processing
Sometimes Navcoin addresses are encoded in a QR code with the navcoin: prefix

Example: `navcoin:NQuwuaonBSft2VV83owJ9XE3twgWtfpoFU` instead of `NQuwuaonBSft2VV83owJ9XE3twgWtfpoFU`

This is a valid format which should be supported when scanning a QR code.

### PR DESCRIPTION
**Pull request by aguycalled**
Fixes #36

### CODE REVIEW

File: contexts/QrProvider.tsx [hunk 1]
```diff
@@ -31,8 +31,11 @@ export const QrProvider = (props: any) => {
       {showQr ? (
         <QRCodeScanner
           onRead={data => {
-            if (bitcore.Address.isValid(data.data)) {
-              setTo(data.data);
+            let toParse = data.data;
+            if (data.data?.substring(0, 8) == 'navcoin:')
```
Comment (tsejerome) [inline contexts/QrProvider.tsx:35]:
```suggestion
            if (data.data?.substring(0, 8) === 'navcoin:')
```

**Review by tsejerome — APPROVED** [review]
